### ISSUE TITLE
Led Instructions

### ISSUE THREAD

**Issue by favarete** [kamaaina/macropad_tool#11]
Hello, thanks for sharing your tool with us!

I want to try it out, but I'm pretty new to Rust and I'm a little confused about how to make a mapping that deals with the LED configuration. For example, how can I program the keys and make all LEDs a solid red.

Can you add some words/example about that, please?

**Comment by kamaaina** [comment]
you don't need a mapping to do this.  i assume you have a product id of 0x8840 so you can run things from the command line like this:
`macropad_tool led 1 red`

see the help by running:
`macropad_tool led -h`

**Comment by kamaaina** [comment]
[Documentation Updated](https://github.com/kamaaina/macropad_tool?tab=readme-ov-file#led-support)
