### ISSUE TITLE
8850 support?

### ISSUE THREAD

**Issue by Kenny-Dave** [kamaaina/macropad_tool#19]
I have a device with a product-id of 8850 that I haven't been able to get working with this code. Any chance of some help to get it going? No problems if not. 

It's a [12 key 4 knob device](url=https://www.amazon.co.uk/gp/product/B0CT81TTDF/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1).

Vendor code: 0x514c
Product code: 0x8850

out-endpoint-address: 0x04
in-endpoint-address: 0x84 or 0x82, I seem to have 2 in lsusb -v. 

I can run program and it gives me the Japanese note to tell me it's programmed, but it doesn't actually change the programming. 

`mint@mint-XXXX:~/Progs/Pad/macropad_tool-main/target/release$ cargo run -- --vendor-id 0x514c --out-endpoint-address 0x04 --in-endpoint-address 0x84 program -c mapping.ron`
`Finished dev [unoptimized + debuginfo] target(s) in 0.03s`
`Running /home/mint/Progs/Pad/macropad_tool-main/target/debug/macropad-tool --vendor-id 0x514c --out-endpoint-address 0x04 --in-endpoint-address 0x84 program -c mapping.ron`
`デバイスのプログラミングが完了しました`

For which I had to bodge in a new line in main.rs at 288:

`0x8850 => k8890::Keyboard8890::new(Some(handle), endpt_addr_out)
            .map(|v| Box::new(v) as Box<dyn Keyboard>),`

Essentially just trying to use the settings for 8890 for what I have. But it doesn't work. Any guidance? I don't know what I'm doing with rust at all.

**Comment by kamaaina** [comment]
unfortunately, i do not have this device so adding support, while not impossible, will be difficult.  it has been my experience thus far that messages between devices differ. this is expected as the hardware on the devices are different (namely the microcontroller). actually, i would  have been very surprised had it actually worked.

the line you added above, is basically saying "program my device like it is an 1189:8890 device" and again most likely will not work. unfortunately, the communication is something non-standard and differs between devices as some support more features than others. 

while it is not all doom and gloom, what we need to do is use wireshark and try to reverse engineer how communication works on 514c:8850 device. i don't mind helping you to try and get it working.

could you also post the output of:
`lsusb -s bus:port -v`

you can get the values of bus and port from 
`lsusb`

curious, where did you get your device from?

**Comment by Kenny-Dave** [comment]
Bus 001
Device 013

I got it on eBay. It's the second unit I've purchased, the first from careforyou arrived broken, who are a large Chinese seller. It's on AliExpress (https://www.aliexpress.com/item/1005006649322050.html) which is maybe the most informative thing for that question.

> actually, i would have been very surprised had it actually worked.

Yes this is the sort of thing that happens when I don't know what I'm doing. I thought I should at least give it a whirl before bothering you to ask for help. Your response is much appreciated. 

`Output of lsb -s 001:013 -v` :

Bus 001 Device 013: ID 514c:8850  USB Composite Device
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x514c 
  idProduct          0x8850 
  bcdDevice            1.00
  iManufacturer           1 
  iProduct                2 USB Composite Device
  iSerial                 3 CD70134330363135
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0042
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      36
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x04  EP 4 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               2.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     207
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)

**Comment by kamaaina** [comment]
thanks for providing that.

since i do not have access to this device, it would be rather difficult to add support at this time. if i can find a cheap one on ebay or somewhere, i might entertain purchasing one.

**Comment by Kenny-Dave** [comment]
Fair dos, I appreciate the comments made in response. I've had a look at wireshark and happy to run analytics or whatever if you decide you want to.
