### ISSUE TITLE
LED color argument only applied to layer 1

### ISSUE THREAD

**Issue by Skitcher** [kamaaina/macropad_tool#21]
Hi, first of all thank you for this amazing tool!

I have a 15 key + 3 knob macropad from aliexpress (HID\VID_1189&PID_8840&REV_0100&MI_01&Col01) and the programming works great. I just noticed an issue with setting the LED mode, where the color argument is only applied to the first layer. For example, `macropad-tool.exe led 1 green` only applies the green color to the first layer and sets layer 2 and 3 to white. It's not bothering me, as with the current range/brightness of the colors I prefer to keep the backlight off, but I just wanted to let you know.

Cheers!

**Comment by Skitcher** [comment]
Just a small update, I played around with the led command. If I follow the `macropad-tool.exe led 1 green` command with a command with  `macropad-tool.exe led X`, where X can be a value of 6-15, the color is applied to all layers. However, this only works for LED mode 1 (constant color) and is not persistent across power cycles.

**Comment by kamaaina** [comment]
sorry for the issue you are experiencing. thank you for contacting me and reporting the problem.

i will take a look and test this issue, though i do not have the exact device you are using so hopefully i am able to recreate the issue and implement a solution given one of the macropads i do have. will update soon.

**Comment by kamaaina** [comment]
i pushed a fix so please update and try it out. the syntax changed so you can run

`macropad-tool led --help` to see the new parameter; essentially you can specify the layer, but default is 1

to program layer 3 with purple, execute this
`macropad-tool led 1 3 purple`

**Comment by Skitcher** [comment]
Thanks for the swift reply, the fix works great! (both different colors and different modes can be written to each layer separately)
