### ISSUE TITLE
15 Key 3 knobs read error

### ISSUE THREAD

**Issue by Skitcher** [kamaaina/macropad_tool#23]
When trying to read out my 15 key + 3 knob macropad from aliexpress (HID\VID_1189&PID_8840&REV_0100&MI_01&Col01) I get the following error:

```
Error: reading macropad configuration

Caused by:
    unable to guess rows/cols for 15 
```
 
Let me know if you need more info, I'm happy to perform tests with my macropad to improve the compatibility of your amazing program.

**Comment by kamaaina** [comment]
thank you for contacting me about this issue.

couple of questions for you since i do not have this device to test with. i have similar ones (1189:8849 and 1189:8890)

1. i assume you ran `macropad-tool read` and got this error. can you please confirm?
2. if you were to program your device (ie. `macropad-tool program -c my_config.ron` did you get the following message?
Unable perform sanity check - device does not support reading of configuration. Programming macropad.

from a few macropads i do have, many have different microcontrollers and thus get programmed different ways. a few of mine support the reading of the configuration and a few  do not. if the answer to the above two questions are yes, unfortunately there are a few conclusions we can infer.

1. you have a device that does not support reading of configuration. would you happen to know if this device supports it? 
2. my code does not support reading data from this device - if it is supported, we could add in support for it if you are willing to help :)

**Comment by Skitcher** [comment]
1. Indeed I get the error when running the command `macropad-tool.exe read`. 
2. When programming the macropad the only output printed to the terminal is a sequence of 15 questionmarks in boxes , which I assume is some issue with unsupported characters in the standard windows terminal. If I try to copy the terminal output to this comment it shows up as `デバイスのプログラミングが完了しました`.

Let me know how I can help you. I can't promise swift replies from my side, but I will try to get any required input when I've got some time to do so :)

**Comment by spikerguy** [comment]
@Skitcher 
Do you have one of these ?

![image](https://github.com/kamaaina/macropad_tool/assets/48839029/0cd82b7e-52a0-4562-b105-bc2badaa2545)

I was able to compile and update the keys so smoothly using the documentation. It was very nice.

I would like to change @kamaaina for all his work.

**Comment by Skitcher** [comment]
@spikerguy I have the same model (although without the USB-dongle) and indeed it works great for the programming of both the keys and backlights. @kamaaina did an amazing job with this piece of software.

**Comment by kamaaina** [comment]
@spikerguy @Skitcher thank you guys for the testing and feedback and for the kind words. i will change the japanese text to print english, but basically it is saying your device was successfully programmed.

i would be interested to know if this model does support "reading of config" and if it does we can work together to get it implemented.

**Comment by spikerguy** [comment]
> @spikerguy @Skitcher thank you guys for the testing and feedback and for the kind words. i will change the japanese text to print english, but basically it is saying your device was successfully programmed.
> 
> i would be interested to know if this model does support "reading of config" and if it does we can work together to get it implemented.

I checked with the vendor and they said it does have read function. Might have to check with windows app which I was able to launch from wine but could detect the device, will try again on windows and try to grab some usb pcap.

**Comment by kamaaina** [comment]
@spikerguy if you could get the capture, that would be a big help

**Comment by spikerguy** [comment]
Hey @kamaaina 

Here is the file from usbcap
[15-3-keypad-port3-1.txt](https://github.com/user-attachments/files/16132512/15-3-keypad-port3-1.txt)

rename it to .pcap please

**Comment by kamaaina** [comment]
@spikerguy thank you for taking the time to get the capture. i have a few questions for you.

1. file name says port 3-1, but it looking at the capture, it seems like device is on 1.4.1 (usb src), can you please confirm.
2. could you provide how your device is setup (ie. how is your device currently programmed when you captured the data)
3. would you be willing to test from a branch? since i don't have the device, i do not want to merge it into the main branch until we get it working. however, this could be a iterative process. my apologizes in advance

**Comment by spikerguy** [comment]
> @spikerguy thank you for taking the time to get the capture. i have a few questions for you.
> 
>     1. file name says port 3-1, but it looking at the capture, it seems like device is on 1.4.1 (usb src), can you please confirm.
> 
>     2. could you provide how your device is setup (ie. how is your device currently programmed when you captured the data)
> 
>     3. would you be willing to test from a branch? since i don't have the device, i do not want to merge it into the main branch until we get it working. however, this could be a iterative process. my apologizes in advance

Hello @kamaaina 

1. ignore the file name.
2. The data was captured on windows pc connected over usb, i checked which port this device is being attached to in usbpcap monitor and then started recording and then plugged in the device and removed it 3 times and then plugged again and opened windows app and read device data 3 times.  the data on the device was uploaded using macropad-tool itself. as I don't have windows pc, I only pull it our of drawer when I need to capture such data.
3. yes I can compile from different branch and test it. I can also provide capture data from linux too.

Thanks for your effort.

**Comment by kamaaina** [comment]
#2 - i am asking if you can provide me with the mapping.ron file that you used to program the device.

I will have to decode the HID data (hopefully it is the same as what i already do for other devices) and i want to verify what i am reading with what you already programmed

**Comment by spikerguy** [comment]
> #2 - i am asking if you can provide me with the mapping.ron file that you used to program the device.
> 
> I will have to decode the HID data (hopefully it is the same as what i already do for other devices) and i want to verify what i am reading with what you already programmed

Sure
here is the mapping that is available on the device when reading on windows.
[mapping.ron.txt](https://github.com/user-attachments/files/16159768/mapping.ron.txt)

**Comment by kamaaina** [comment]
could you please checkout and compile the branch called 

> read-config-8840

 and try running `macropad-tool read`

**Comment by spikerguy** [comment]
Hey @kamaaina 

```
[furkan@furkan-pc release]$ ./macropad-tool read
thread 'main' panicked at src/main.rs:292:46:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

here

**Comment by kamaaina** [comment]
thanks for trying. instead of doing a release build, could you just do a debug build? i pushed a new commit, please update and you can then run with:

`cargo run -- read`

**Comment by spikerguy** [comment]
@kamaaina 
Thanks for update 

Works fine 

```
 macropad_tool]$ cargo run -- read
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/macropad-tool read`
(
    device: (
        orientation: Normal,
        rows: 3,
        cols: 5,
        knobs: 3,
    ),
    layers: [
        (
            buttons: [
                [(delay: 0, mapping: "1"), (delay: 0, mapping: "f"), (delay: 0, mapping: "k"), (delay: 0, mapping: "alt-4"), (delay: 0, mapping: "alt-1")],
                [(delay: 0, mapping: "alt-5"), (delay: 0, mapping: "c"), (delay: 0, mapping: "h"), (delay: 0, mapping: "0"), (delay: 0, mapping: "alt-2")],
                [(delay: 0, mapping: "alt-6"), (delay: 0, mapping: "d"), (delay: 0, mapping: "a"), (delay: 0, mapping: "0"), (delay: 0, mapping: "alt-3")],
            ],
            knobs: [
                (ccw: (delay: 0, mapping: "wheeldown"), press: (delay: 0, mapping: "mute"), cw: (delay: 0, mapping: "wheelup")),
                (ccw: (delay: 0, mapping: "wheeldown"), press: (delay: 0, mapping: "mute"), cw: (delay: 0, mapping: "wheelup")),
                (ccw: (delay: 0, mapping: "wheeldown"), press: (delay: 0, mapping: "mute"), cw: (delay: 0, mapping: "wheelup")),
            ],
        ),
        (
            buttons: [
                [(delay: 0, mapping: "2"), (delay: 0, mapping: "f"), (delay: 0, mapping: "k"), (delay: 0, mapping: "space"), (delay: 0, mapping: "t")],
                [(delay: 0, mapping: "e"), (delay: 0, mapping: "c"), (delay: 0, mapping: "h"), (delay: 0, mapping: "k"), (delay: 0, mapping: "a")],
                [(delay: 0, mapping: "r"), (delay: 0, mapping: "d"), (delay: 0, mapping: "a"), (delay: 0, mapping: "m"), (delay: 0, mapping: "e")],
            ],
            knobs: [
                (ccw: (delay: 0, mapping: "h"), press: (delay: 0, mapping: "2"), cw: (delay: 0, mapping: "t")),
                (ccw: (delay: 0, mapping: "h"), press: (delay: 0, mapping: "2"), cw: (delay: 0, mapping: "t")),
                (ccw: (delay: 0, mapping: "h"), press: (delay: 0, mapping: "2"), cw: (delay: 0, mapping: "t")),
            ],
        ),
        (
            buttons: [
                [(delay: 0, mapping: "3"), (delay: 0, mapping: "f"), (delay: 0, mapping: "k"), (delay: 0, mapping: "space"), (delay: 0, mapping: "t")],
                [(delay: 0, mapping: "e"), (delay: 0, mapping: "c"), (delay: 0, mapping: "h"), (delay: 0, mapping: "k"), (delay: 0, mapping: "a")],
                [(delay: 0, mapping: "r"), (delay: 0, mapping: "d"), (delay: 0, mapping: "a"), (delay: 0, mapping: "m"), (delay: 0, mapping: "e")],
            ],
            knobs: [
                (ccw: (delay: 0, mapping: "f"), press: (delay: 0, mapping: "3"), cw: (delay: 0, mapping: "k")),
                (ccw: (delay: 0, mapping: "f"), press: (delay: 0, mapping: "3"), cw: (delay: 0, mapping: "k")),
                (ccw: (delay: 0, mapping: "f"), press: (delay: 0, mapping: "3"), cw: (delay: 0, mapping: "k")),
            ],
        ),
    ],
)
```

**Comment by kamaaina** [comment]
@spikerguy thanks for testing and for providing the captures so we could get this working. it has been merged with the main branch, so please give it another try using the main branch when you get a chance. if it still works, we should be able to close this issue.

**Comment by spikerguy** [comment]
Yeayyyy @kamaaina 

```
[furkan@furkan-pc macropad_tool]$ git branch
* main
[furkan@furkan-pc macropad_tool]$ cargo run -- read
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/macropad-tool read`
(
    device: (
        orientation: Normal,
        rows: 3,
        cols: 5,
        knobs: 3,
    ),
    layers: [
        (
            buttons: [
                [(delay: 0, mapping: "1"), (delay: 0, mapping: "f"), (delay: 0, mapping: "k"), (delay: 0, mapping: "alt-4"), (delay: 0, mapping: "alt-1")],
                [(delay: 0, mapping: "alt-5"), (delay: 0, mapping: "c"), (delay: 0, mapping: "h"), (delay: 0, mapping: "0"), (delay: 0, mapping: "alt-2")],
                [(delay: 0, mapping: "alt-6"), (delay: 0, mapping: "d"), (delay: 0, mapping: "a"), (delay: 0, mapping: "0"), (delay: 0, mapping: "alt-3")],
            ],
            knobs: [
                (ccw: (delay: 0, mapping: "wheeldown"), press: (delay: 0, mapping: "mute"), cw: (delay: 0, mapping: "wheelup")),
                (ccw: (delay: 0, mapping: "wheeldown"), press: (delay: 0, mapping: "mute"), cw: (delay: 0, mapping: "wheelup")),
                (ccw: (delay: 0, mapping: "wheeldown"), press: (delay: 0, mapping: "mute"), cw: (delay: 0, mapping: "wheelup")),
            ],
        ),
        (
            buttons: [
                [(delay: 0, mapping: "2"), (delay: 0, mapping: "f"), (delay: 0, mapping: "k"), (delay: 0, mapping: "space"), (delay: 0, mapping: "t")],
                [(delay: 0, mapping: "e"), (delay: 0, mapping: "c"), (delay: 0, mapping: "h"), (delay: 0, mapping: "k"), (delay: 0, mapping: "a")],
                [(delay: 0, mapping: "r"), (delay: 0, mapping: "d"), (delay: 0, mapping: "a"), (delay: 0, mapping: "m"), (delay: 0, mapping: "e")],
            ],
            knobs: [
                (ccw: (delay: 0, mapping: "h"), press: (delay: 0, mapping: "2"), cw: (delay: 0, mapping: "t")),
                (ccw: (delay: 0, mapping: "h"), press: (delay: 0, mapping: "2"), cw: (delay: 0, mapping: "t")),
                (ccw: (delay: 0, mapping: "h"), press: (delay: 0, mapping: "2"), cw: (delay: 0, mapping: "t")),
            ],
        ),
        (
            buttons: [
                [(delay: 0, mapping: "3"), (delay: 0, mapping: "f"), (delay: 0, mapping: "k"), (delay: 0, mapping: "space"), (delay: 0, mapping: "t")],
                [(delay: 0, mapping: "e"), (delay: 0, mapping: "c"), (delay: 0, mapping: "h"), (delay: 0, mapping: "k"), (delay: 0, mapping: "a")],
                [(delay: 0, mapping: "r"), (delay: 0, mapping: "d"), (delay: 0, mapping: "a"), (delay: 0, mapping: "m"), (delay: 0, mapping: "e")],
            ],
            knobs: [
                (ccw: (delay: 0, mapping: "f"), press: (delay: 0, mapping: "3"), cw: (delay: 0, mapping: "k")),
                (ccw: (delay: 0, mapping: "f"), press: (delay: 0, mapping: "3"), cw: (delay: 0, mapping: "k")),
                (ccw: (delay: 0, mapping: "f"), press: (delay: 0, mapping: "3"), cw: (delay: 0, mapping: "k")),
            ],
        ),
    ],
)
```

Test successful. We can close this issue.

**Comment by kamaaina** [comment]
@spikerguy thank you for your help with this!
