### ISSUE TITLE
libusb architecture error when compiling on mac arm64

### ISSUE THREAD

**Issue by tg44** [kamaaina/macropad_tool#29]
I get `ld: warning: ignoring file '/opt/homebrew/Cellar/libusb/1.0.27/lib/libusb-1.0.0.dylib': found architecture 'arm64', required architecture 'x86_64'` when I try to build.

Is there any idea, how can I solve this problem? I tried to reinstall libusb. Also, googling did not helped me.

**Comment by kamaaina** [comment]
try deleting your Cargo.lock file and rebuilding

**Comment by kamaaina** [comment]
@tg44 were you able to build?

**Comment by tg44** [comment]
Nope, it is the same, after I deleted the Cargo.lock, the regenerated (updated) version has no version changes with libusb.

BUT this worked;
```
rustup target add aarch64-apple-darwin
cargo build --release --target=aarch64-apple-darwin
target/aarch64-apple-darwin/release/macropad-tool validate -h
```
So for some reasons, I needed to explicitly tell the rust compiler to compile against apple silicon even if I'm on apple silicon...
