### ISSUE TITLE
Media keys >0xFF cannot be programmed

### ISSUE THREAD

**Issue by npiegdon** [kamaaina/macropad_tool#30]
If you try to use one of the media keys in the upper part of the allowed range (say, "calculator" with a value of 0x192), the config file will validate just fine, but upon trying to program the device I am getting:
```
thread 'main' panicked at src/keyboard/k8890.rs:197:65:
called `Option::unwrap()` on a `None` value
```
I'm not familiar with Rust but I'm guessing it's the `to_u8` part that is failing because 0x192 is larger than a u8 can hold.

(Thank you for this tool!  Everything else is working great.)

**Comment by kamaaina** [comment]
thanks for reporting this. 

to be honest, i have not done much testing on windows :) but that byte sequence should be correct at byte 10 should be 0x01 and byte 11 should be 0x92 which are sufficient to hold in u8 data type. regardless, it seems it is not working and something is crashing so i will try this out as i have a 0x8890 device when i get a chance and report back

**Comment by kamaaina** [comment]
after looking at this a bit more, it appears what you stated is correct. media keys > 0xff cannot be programmed, but that is because i believe the device does not support it. using the manufacturers software the only multimedia keys they support are play/pause, prev song, next song, mute, volume up and volume down.

i will make a change to validate to check for this on this device. other devices (namely pid 0x884x)  support this. sorry, this was an oversight on my part when i added support for the 0x8890 device

**Comment by npiegdon** [comment]
Thanks for looking into this!  I saw that one of the manufacturer's apps (the "new version" that looks like it has a Qt-based UI) had a calculator key but after checking again I wasn't able to get it to connect to my 0x8890 device.

Checking their older, .NET-based Windows Forms app which *does* work with my device, there isn't a calculator key so I suspect you are right that it doesn't support wider-than-8-bit key codes.

I found a workaround: I just treat the buttons as F13, F14, etc. and use AutoHotkey on Windows to intercept the generic presses and turn them into whatever I like.  So I got my calculator button in the end! 🤣

Thanks again.

**Comment by kamaaina** [comment]
yay! glad you found a creative way to get it to work.

**Comment by fat115** [comment]
Hello,
Same problem here with a '4*3+2' pad (1189:8842).
Simple mapping works :

> buttons: [
>     [(delay: 0, mapping: "a"), (delay: 0, mapping: "b"), (delay: 0, mapping: "c"), (delay: 0, mapping: "d")],
>     [(delay: 0, mapping: "e"), (delay: 0, mapping: "f"), (delay: 0, mapping: "g"), (delay: 0, mapping: "h")],
>     [(delay: 0, mapping: "i"), (delay: 0, mapping: "j"), (delay: 0, mapping: "k"), (delay: 0, mapping: "l")],

Introducing a simple "calculator" key > 0xFF

> buttons: [
>     [(delay: 0, mapping: "calculator"), (delay: 0, mapping: "b"), (delay: 0, mapping: "c"), (delay: 0, mapping: "d")],
>     [(delay: 0, mapping: "e"), (delay: 0, mapping: "f"), (delay: 0, mapping: "g"), (delay: 0, mapping: "h")],
>     [(delay: 0, mapping: "i"), (delay: 0, mapping: "j"), (delay: 0, mapping: "k"), (delay: 0, mapping: "l")],

results in following error when trying to program :

> thread 'main' panicked at src/keyboard/k884x.rs:387:65:
> called `Option::unwrap()` on a `None` value
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::panicking::panic
>    3: core::option::unwrap_failed
>    4: macropad_tool::keyboard::k884x::Keyboard884x::build_key_msg
>    5: <macropad_tool::keyboard::k884x::Keyboard884x as macropad_tool::keyboard::Keyboard>::program
>    6: macropad_tool::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

I'm sure that my device supports this key code as it works using kriomant's https://github.com/kriomant/ch57x-keyboard-tool
In fact, I was able to add support for many other media keys (see below) for my model but only through USB connection. It doesn't work trough bluetooth. Your tool seems to work trough USB and Bluetooth but doesn't support key > 0xFF.
All keys I successfully add to my device :

```
    BalanceRight = 0x150,
    BalanceLeft = 0x151,
    BassIncrement = 0x152,
    BassDecrement = 0x153,
    TrebleIncrement = 0x154,
    TrebleDecrement = 0x155,
    // KEY_BUTTONCONFIG
    LaunchButtonConfigurationTool = 0x181,
    // KEY_BOOKMARKS
    Favorites = 0x182,
    // KEY_CONFIG
    ConsumerControlConfiguration = 0x183,
    // KEY_WORDPROCESSOR
    WordProcessor = 0x184,
    // KEY_EDITOR
    TextEditor = 0x185,
    // KEY_SPREADSHEET
    Spreadsheet = 0x186,
    // KEY_GRAPHICSEDITOR
    GraphicsEditor = 0x187,
    // KEY_PRESENTATION
    PresentationApp = 0x188,
    // KEY_DATABASE
    DatabaseApp = 0x189,
    // KEY_MAIL
    EmailReader = 0x18a,
    // KEY_NEWS
    NewsReader = 0x18b,
    // KEY_VOICEMAIL
    VoiceMail = 0x18c,
    // KEY_ADDRESSBOOK
    ContactsAddressbook = 0x18d,
    // KEY_CALENDAR
    CalendarSchedule = 0x18e,
    // KEY_TASKMANAGER
    TaskProjectManager = 0x18f,
    // KEY_JOURNAL
    LogJournalTimeCard = 0x190,
    // KEY_FINANCE
    CheckBookFinance = 0x191,
    // KEY_CALC
    Calculator = 0x192,
    // KEY_PLAYER
    AVCapturePlayback = 0x193,
    // KEY_FILE
    LocMachineBrowser = 0x194,
    // KEY_WWW
    InternetBrowser = 0x196,
    // KEY_CHAT
    NetworkChat = 0x199,
    // KEY_LOGOFF
    Logoff = 0x19c,
    // KEY_SCREENLOCK
    ScreenLock = 0x19e,
    // KEY_CONTROLPANEL
    ControlPanel = 0x19f,
    // KEY_APPSELECT
    SelectTaskApplication = 0x1a2,
    // KEY_NEXT
    NextTaskApplication = 0x1a3,
    // KEY_PREVIOUS
    PreviousTaskApplication = 0x1a4,
    // KEY_HELP
    IntegratedHelpCenter = 0x1a6,
    // KEY_DOCUMENTS
    Documents = 0x1a7,
    // KEY_SPELLCHECK
    Spellcheck = 0x1ab,
    // KEY_KEYBOARD
    KeyboardLayout = 0x1ae,
    // KEY_SCREENSAVER
    Screensaver = 0x1b1,
    // KEY_FILE
    FileBrowser = 0x1b4,
    // KEY_IMAGES
    ImageBrowser = 0x1b6,
    // KEY_AUDIO
    AudioBrowser = 0x1b7,
    // KEY_VIDEO
    MovieBrowser = 0x1b8,
    // KEY_MESSENGER
    InstantMessaging = 0x1bc,
    // KEY_INFO
    OEMFeaturesTipsTutoriBrowser = 0x1bd,
    // KEY_ASSISTANT
    ContextAwareDesktopAssistant = 0x1cb,
    Back = 0x224,

With kriomant's tool, the problem was solved with this PR : https://github.com/kriomant/ch57x-keyboard-tool/pull/23
I'm not familiar with Rust so I don' know how to port this to your tool..
Hope you'll ba able to.
```

**Comment by kamaaina** [comment]
@fat115 thanks for the media codes. for now, try just doing a simple calculator using the media-keys branch as i just pushed a change.

if that works, i can add support for the rest and merge it with the trunk, but wanted to make sure one media key works. i tested with my 1189:8840 macropad and it works. i will also need to add support for 1189:8890 as well before merging with trunk.

please let me know how things go with your testing

**Comment by fat115** [comment]
I've just tried and it works !
I also tried adding some other media codes (0x1##) and they also work.
But there's a side-effect/limit : volume media codes (0xe9 & 0xea) don't work anymore ; "Back" media code (0x224) (see above) doesn't work.
There's no error on programming but they then produce a "KEY_UNKNOWN"  with evtest /dev/impunt/eventX

**Comment by kamaaina** [comment]
sorry about that. pushed another fix to the same branch. this should handle the cases for 0x1xx (calculator, etc.) and 0x2xx (back, etc.) and fixed the volume up/down.

could you please test again?

**Comment by kamaaina** [comment]
merged to main branch
