### ISSUE TITLE
Is there a possibility of doing custom macros

### ISSUE THREAD

**Issue by SergioBarbero** [kamaaina/macropad_tool#31]
HI, thank you for this project, it's definitely great!

I wonder if there's the possibility of doing things like opening applications or running scripts

**Comment by kamaaina** [comment]
you can certainly do this with things like QMK and ZMK, but that is firmware that you flash to your keyboard. some macropads support QMK, but what my tool does is just map keys to a button press as that is agnostic to custom keyboards. basically the spec for a usb keyboard is what is supported.
